name: CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install liburing
        run: mkdir liburing
          && (curl -fsSL https://github.com/axboe/liburing/tarball/master | tar xz -C liburing --strip-components 1)
          && cd liburing
          && ./configure
          && make -j$(nproc)
          && sudo make -j$(nproc) install

      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
